version: '3.8'

services:
  web:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    command: gunicorn PerfectParking.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
    networks:
      - parking_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - parking_network

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    networks:
      - parking_network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  celery:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    command: celery -A PerfectParking worker -l INFO
    env_file:
      - ../.env
    depends_on:
      - redis
      - db
    networks:
      - parking_network

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - parking_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  parking_network:
    driver: bridge 