[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmd = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[start]
cmd = "export DJANGO_SETTINGS_MODULE=VehiScan.settings && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn vehiscanWebsite.wsgi:application --bind 0.0.0.0:$PORT"