# Generated by Django 5.1.5 on 2025-01-23 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=255)),
                ('isPaidParking', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('image', models.ImageField(blank=True, upload_to='images/parking-lot/')),
                ('parking_spaces', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLotMonitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('probabilityParkingAvailable', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('free_parking_spaces', models.IntegerField(default=0)),
                ('dateTimeLastUpdated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='images/parking-lot-monitor/')),
                ('parkingLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carParkingFrontend.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLotLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('free_parking_spaces', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carParkingFrontend.parkinglot')),
                ('logged_by_monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carParkingFrontend.parkinglotmonitor')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRequestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_of_interest_latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('area_of_interest_longitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('user_ip_address', models.CharField(max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
