name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Check code formatting
      run: |
        black . --check
        isort . --check-only

    - name: Run security checks
      run: |
        bandit -r .
        safety check

    - name: Check dependencies
      run: |
        pip-audit
        pip check

    - name: Validate migrations
      run: |
        python manage.py makemigrations --check
        python manage.py migrate --check

    - name: Run type checking
      run: |
        mypy . 